#!/usr/bin/env python

Import('env')
Import('env_modules')

env_tove = env_modules.Clone()

env_tove.add_source_files(env.modules_sources, "*.cpp")
env_tove.add_source_files(env.modules_sources, "godot/*.cpp")

env_tove.add_source_files(env.modules_sources, "src/cpp/*.cpp")
env_tove.add_source_files(env.modules_sources, "src/cpp/mesh/*.cpp")
env_tove.add_source_files(env.modules_sources, "src/cpp/shader/*.cpp")
env_tove.add_source_files(env.modules_sources, "src/thirdparty/*.cpp")

env_tove.Append(CXXFLAGS=['-std=c++11'])
